services:
  - type: web
    name: devision-frontend-jm
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_STRIPE_PUBLISHABLE_KEY
        sync: false
    healthCheckPath: /health
