services:
  - type: web
    name: devision-frontend-jm
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://jm-gateway.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
